language: php

php:
  - 7.4

os: linux

before_install: cd backend

before_script:
  - composer install
  - cp .env.example .env
  - sudo mysql -e 'create database forge;'
  - composer self-update
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit
