language: php

php:
  - 7.4

os: linux

before_install: cd backend

before_script:
  - composer install
  - cp .env.example .env
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit
