version: "3.7"
services:
  app:
    build:
      args:
        user: vimaguelo
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: soen341
    container_name: soen341-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - soen341

  db:
    image: mysql:5.7
    container_name: soen341-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - soen341
    ports:
      - "3308:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    networks:
      - soen341
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: default
      PMA_PASSWORD: secure
    ports:
      - "8080:80"

  nginx:
    image: nginx:alpine
    container_name: soen341-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - soen341

networks:
  soen341:
    driver: bridge
